[package]
name = "silica-export"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
image = { version = "=0.25.6", default-features = false, features = ["jpeg"] }
silica-render = { path = "../silica-render" }
sha2 = { version = "0.10.9", default-features = false, features = ["std"] }
