[package]
name = "silica-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
rusqlite = { version = "0.40.1", default-features = false, features = ["bundled"] }
silica-catalog = { path = "../silica-catalog" }
