[package]
name = "silica-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
silica-decode = { path = "../silica-decode" }
silica-edit = { path = "../silica-edit" }
silica-export = { path = "../silica-export" }
silica-render = { path = "../silica-render" }
silica-storage = { path = "../silica-storage" }
serde_json = "1.0.150"

[dev-dependencies]
image = { version = "=0.25.6", default-features = false, features = ["jpeg"] }
